### ISSUE TITLE
Shows you are offline when ipv4.icanhazip.com was returning slow response

### ISSUE THREAD

**Issue by pawneetdev** [cwise89/react-detect-offline#75] opened 2021-02-19 09:15 UTC
Due to icanhazip not working properly our page was showing you are offline.

Can some fallback URL be used to double-check the status of the internet?

**Comment by heenasangtani** [comment] 2021-02-19 09:24
Having the same issue

**Comment by VijayJaybhay** [comment] 2021-02-19 11:21
Having the same issue for the last few hours

**Comment by katfastovets** [comment] 2021-02-19 11:56
Have the same issue during last 3 hours.
I've increased timeout value to 7000 and it works for now.
And also Detector component has onChange event, where you can write your own fallback with extra polling some other site or use navigator.onLine.

**Comment by heenasangtani** [comment] 2021-02-19 12:27
> Have the same issue during last 3 hours.
> I've increased timeout value to 7000 and it works for now.
> And also Detector component has onChange event, where you can write your own fallback with extra polling some other site or use navigator.onLine.

I am using Online and Offline without any props do you help me in this.

**Comment by katfastovets** [comment] 2021-02-19 12:51
> > Have the same issue during last 3 hours.
> > I've increased timeout value to 7000 and it works for now.
> > And also Detector component has onChange event, where you can write your own fallback with extra polling some other site or use navigator.onLine.
> 
> I am using Online and Offline without any props do you help me in this.

You can pass prop polling to Online and Oflline, as the doc says

**Comment by VijayJaybhay** [comment] 2021-02-19 12:53
In my case, I have disabled polling which causes the library to use browser-specific online and offline events. I referred to support docs (https://caniuse.com/online-status) which shows that support is available since many previous versions in popular browsers. Consider switching to no polling if you are not supporting older versions of different browsers.

**Comment by Serginh0** [comment] 2021-02-19 13:31
some good soul, could you pass a website that you use to check online / offline? it would be a good one, if the site was from Google.
Sorry for the bad English

**Comment by Serginh0** [comment] 2021-02-19 13:55
I try to use https://www.google.com/ mas CORS error, could someone help?

**Comment by mdodge-ecgrow** [comment] 2021-02-19 17:33
Having the same issue in my app.  Thought it was my connection, but then I saw the errors in the console.

**Comment by lesmo** [comment] 2021-02-19 17:42
How about making the domain/server configurable? It's scary to see this could take down stuff...

**Comment by chrisbolin** [comment] 2021-02-19 18:35
omg yall. it's already configurable. rtfm 😂

**Comment by chrisbolin** [comment] 2021-02-19 18:36
@lesmo check this out: https://github.com/cwise89/react-detect-offline#props

specifically the pooling url 👼 

I has to be easier to read a short readme than to search for an issue and comment on it, right?

**Comment by lesmo** [comment] 2021-02-19 18:57
> @lesmo check this out: https://github.com/cwise89/react-detect-offline#props
> 
> specifically the pooling url 👼 
> 
> I has to be easier to read a short readme than to search for an issue and comment on it, right?

lol it happens, a college found a bug caused by this lib and I trusted he already discarded stuff from the Readme 🤷‍♂️

**Comment by lesmo** [comment] 2021-02-19 19:52
So, upon further inspection, `canihazip.com` is no longer functional. I've sent PR #76 with further info.

**Comment by katfastovets** [comment] 2021-02-19 20:06
> So, upon further inspection, `canihazip.com` is no longer functional. I've sent PR #76 with further info.

https://github.com/major/icanhaz/issues/21
Looks like they had trouble with DDoS attacks.

**Comment by chrisbolin** [comment] 2021-02-19 20:15
> [major/icanhaz#21](https://github.com/major/icanhaz/issues/21)
> Looks like they had trouble with DDoS attacks.

I feel bad for them :( 

I think this means we'll likely move to a default that is run by a larger organization and can guarantee better uptime. I've already talked with @cwise89 and he has some ideas.

**Comment by lesmo** [comment] 2021-02-19 20:16
> > So, upon further inspection, `canihazip.com` is no longer functional. I've sent PR #76 with further info.
> 
> [major/icanhaz#21](https://github.com/major/icanhaz/issues/21)
> Looks like they had trouble with DDoS attacks.

It's currently pointing to some pastry stuff, now I want some cookies 😂

In all seriousness though, it appears `ipify.org` is more reliable. I was going to suggest using Google's or Microsoft's service instead, but probably their EULA forbids this and probably some CORS won't allow it. I once used it on a React Native app... but in that, your requests don't really care about CORS.

**Comment by major** [comment] 2021-02-19 22:37
Howdy from the maintainer of icanhazip.com! 🤠

I've moved icanhazip to Cloudflare's workers (thanks to Cloudflare for sponsoring the site), so the response time should be better now. I'm always open to feedback!

**Comment by heenasangtani** [comment] 2021-02-20 03:41
> > > Have the same issue during last 3 hours.
> > > I've increased timeout value to 7000 and it works for now.
> > > And also Detector component has onChange event, where you can write your own fallback with extra polling some other site or use navigator.onLine.
> > 
> > 
> > I am using Online and Offline without any props do you help me in this.
> 
> You can pass prop polling to Online and Oflline, as the doc says

In mobile firefox it is working fine (only issue in chrome android) but when I pass Polling Props it stops working on firefox :P

**Comment by chrisbolin** [comment] 2021-02-20 20:06
this has been fixed with `v2.4.2`. thank you to all of you who reported this and did research, especially @lesmo who found a viable alternative.

**if you cannot upgrade, that's ok!** just change `polling.url` to a reliable CORS-capable endpoint. we are now using `https://api.ipify.org/?format=json`

**Closed by chrisbolin** 2021-02-20 20:06 UTC

**Comment by jpriollaud** [comment] 2021-02-21 02:23
i upgraded to v2.4.2 and somehow on mobile chrome my offline component renders after 5 seconds and stays rendered permanently.  on desktop chrome os with chrome browser it works normally.

**Comment by jpriollaud** [comment] 2021-02-21 19:44
`<Detector polling={{url: "https://api.ipify.org/?format=json"}} ... />` and CSP connect-src: 'https://api.ipify.org' does not work.  Offline is always shown on mobile chrome, Windows chrome, but not always shown on desktop Chrome OS chrome.

CSP won't allow query string.

`<Detector polling={{url: "https://ipv4.icanhazip.com"}} ... />` and CSP connect-src: 'https://ipv4.icanhazip.com' works perfectly on all user agents.

I'm probably missing something obvious.

**Comment by jpriollaud** [comment] 2021-02-21 21:04
For me in both v2.4.0 and v2.4.2 only `<Detector polling={{url: "https://ipv4.icanhazip.com"}} ... />` works.  I tried multiple endpoints at ipify.org, polling props vs no polling props, tried multiple CSP connect-src configurations.

On the following user agents the ip checkers https://www.ipify.org/ and https://checkip.amazonaws.com/ do not work (offline component perma-renders): Windows Chrome.  Android Chrome.  They did work on desktop Chrome OS Chrome however.

I'm baffled as to what I'm doing wrong.  It's probably something obvious.  I'm just going with icanhazip for the time being.

This component has worked great for us for the past year until the icanhazip outage.
